/* ============================================================
   GLOBAL NAVIGATION + AUTH MENU
   Loaded on every public page.
   ============================================================ */

const RK_MENU_GROUPS = [
  { slug: 'racing-kings-menu', label: 'Racing Kings', items: [
    { slug: 'leaderboard', label: 'Leaderboards', icon: '🏆', description: 'View the site\'s Racing Kings rankings and live player ratings.' },
    { slug: 'hall-of-fame', label: 'Hall of Fame', icon: '👑', description: 'Explore the players and achievements that have shaped Racing Kings.' },
    { slug: 'players', label: 'Players', icon: '👥', description: 'Browse officially recognized players and open individual profiles.' }
  ]},
  { slug: 'titles-menu', label: 'Titles', items: [
    { slug: 'titles', label: 'Titles', icon: '♛', description: 'See every title tier, its requirements, and current holders.' },
    { slug: 'title-checker', label: 'Title Checker', icon: '✓', description: 'Check a Lichess Racing Kings player against the current criteria.' }
  ]},
  { slug: 'community-menu', label: 'Community', items: [
    { slug: 'team', label: 'Lichess Team', icon: '👥', description: 'Visit the Racing Kings Master team and view its live community statistics.' },
    { slug: 'about', label: 'About', icon: 'ℹ', description: 'Learn what the project is, how it works, and where it is heading.' }
  ]},
  { slug: 'u2000-menu', label: 'U2000', items: [
    { slug: 'u2000-competitions', label: 'U2000 Competitions', icon: '🏁', description: 'Find competitions and events designed for players rated below 2000.' },
    { slug: 'u2000-learning', label: 'U2000 Learning', icon: '📚', description: 'Training resources, guides, and practical ideas for improving below 2000.' },
    { slug: 'u2000-other', label: 'Other', icon: '✨', description: 'Explore other U2000 projects, resources, and community features.' }
  ]},
  { slug: 'account-menu', label: 'Account', items: [] }
];
(function setTheme(){document.documentElement.setAttribute('data-theme',localStorage.getItem('rk-theme')||'dark');})();
(function initGlobalMenu(){
  const pageUrl=s=>s==='index'?'index.html':`${s}.html`;
  const makeLink=(l,h)=>{const a=document.createElement('a');a.href=h;a.textContent=l;return a;};
  const loadScript=src=>new Promise((resolve,reject)=>{const e=document.querySelector(`script[src="${src}"]`);if(e)return e.dataset.loaded==='true'?resolve():(e.addEventListener('load',resolve,{once:true}),e.addEventListener('error',reject,{once:true}));const s=document.createElement('script');s.src=src;s.async=false;s.onload=()=>{s.dataset.loaded='true';resolve();};s.onerror=reject;document.head.appendChild(s);});
  function ensureLogoStyle(){if(document.getElementById('rk-logo-global-style'))return;const s=document.createElement('style');s.id='rk-logo-global-style';s.textContent='.top-bar{min-height:60px!important}.nav-left{min-width:0!important;overflow:hidden!important}.rk-brand{display:flex!important;align-items:center!important;justify-content:flex-start!important;flex:0 1 auto!important;width:190px!important;height:44px!important;max-width:190px!important;max-height:44px!important;min-width:0!important;min-height:0!important;overflow:hidden!important;text-decoration:none!important}.rk-brand img{display:block!important;width:100%!important;height:100%!important;min-width:0!important;min-height:0!important;max-width:190px!important;max-height:44px!important;object-fit:contain!important;object-position:left center!important;flex:none!important}@media(max-width:700px){.rk-brand{width:145px!important;height:38px!important;max-width:145px!important;max-height:38px!important}.rk-brand img{max-width:145px!important;max-height:38px!important}}@media(max-width:430px){.rk-brand{width:112px!important;height:34px!important;max-width:112px!important;max-height:34px!important}.rk-brand img{max-width:112px!important;max-height:34px!important}}';document.head.appendChild(s);}
  async function deps(){if(!window.supabase)await loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2');if(!window.rkSupabase||!window.rkAuth)await loadScript('js/supabase.js');}
  function logo(){ensureLogoStyle();const h=document.querySelector('header.top-bar,header,.site-header,.topbar,.navbar,.nav-bar');if(!h)return;let left=h.querySelector('.nav-left');if(!left){left=document.createElement('div');left.className='nav-left';h.prepend(left);}let a=h.querySelector('.rk-brand');if(!a){a=document.createElement('a');a.className='rk-brand';a.href='index.html';a.setAttribute('aria-label','The Racing Kings Master — Home');a.title='The Racing Kings Master — Home';a.innerHTML='<img src="Images/Home logo.png" alt="The Racing Kings Master" width="190" height="44">';}if(a.parentElement!==left)left.prepend(a);const img=a.querySelector('img');if(img){img.src='Images/Home logo.png';img.alt='The Racing Kings Master';img.width=190;img.height=44;}a.href='index.html';}
  function readProfileStats(){const rows=[...document.querySelectorAll('#statsGrid .stat-item')];const get=(label)=>{const row=rows.find(r=>r.querySelector('.stat-label')?.textContent?.trim().toLowerCase()===label.toLowerCase());return row?.querySelector('.stat-value')?.textContent?.replace(/[^0-9.-]/g,'')||'';};return {games:Number(get('Total Games'))||0,peakRating:Number(get('Peak Rating'))||0};}
  async function syncHomepageTitleStats(){if(!window.rkSupabase||!document.getElementById('statTitled'))return;try{const {data,error}=await window.rkSupabase.from('titles').select('id,user_id');if(error)throw error;const rows=Array.isArray(data)?data:[];const titledPlayers=new Set(rows.map(r=>r.user_id).filter(Boolean)).size;const awarded=rows.length;const titledEl=document.getElementById('statTitled');const awardedEl=document.getElementById('statTitlesAwarded');if(titledEl)titledEl.textContent=titledPlayers.toLocaleString();if(awardedEl)awardedEl.textContent=awarded.toLocaleString();}catch(e){console.warn('Could not sync homepage title statistics:',e);}}
  async function syncTitlesPage(){const grid=document.getElementById('titlesGrid');if(!grid||!window.rkSupabase)return;try{const [titlesResult,profilesResult]=await Promise.all([window.rkSupabase.from('titles').select('user_id,title,awarded_at').order('awarded_at',{ascending:true}),window.rkSupabase.from('profiles').select('id,username')]);if(titlesResult.error)throw titlesResult.error;if(profilesResult.error)throw profilesResult.error;const profileMap=new Map((profilesResult.data||[]).map(p=>[p.id,p.username]));const holderMap=new Map();(titlesResult.data||[]).forEach(record=>{const username=profileMap.get(record.user_id);if(!username)return;const code=String(record.title||'').trim().toUpperCase();if(!code)return;if(!holderMap.has(code))holderMap.set(code,[]);holderMap.get(code).push(username);});grid.querySelectorAll('.title-card').forEach(card=>{const badge=card.querySelector('.title-badge-large');if(!badge)return;const code=badge.textContent.trim().toUpperCase();const holders=[...new Set(holderMap.get(code)||[])];const countEl=card.querySelector('.title-holder-count strong');const list=card.querySelector('.holders-list');if(countEl)countEl.textContent=holders.length;if(list){list.replaceChildren();if(!holders.length){const empty=document.createElement('span');empty.className='no-holders';empty.textContent='No current holders';list.appendChild(empty);}else holders.forEach(username=>{const a=document.createElement('a');a.className='holder-chip';a.href=`profile.html?u=${encodeURIComponent(username)}`;a.textContent=username;list.appendChild(a);});}});[...grid.querySelectorAll('.title-card .title-reqs li')].forEach(li=>{if(li.innerHTML.includes('3+0 or faster'))li.innerHTML=li.innerHTML.replaceAll('3+0 or faster','3+0, 3+2, or 5+0');});const blitzItem=[...document.querySelectorAll('.common-list li')].find(li=>li.textContent.toLowerCase().includes('blitz norms'));if(blitzItem)blitzItem.innerHTML='<strong>Blitz norms</strong> = tournaments using 3+0, 3+2, or 5+0 time controls';}catch(e){console.warn('Could not sync title holders from Supabase:',e);}}
  async function syncProfilePage(user){
    const output=document.getElementById('profileOutput');
    const titleEl=document.getElementById('siteTitlesContent');
    if(!output||!titleEl||!window.rkSupabase)return;
    const refreshProfileTitles=async()=>{
      const input=document.getElementById('usernameInput');const username=input?.value?.trim();if(!username)return;
      try{const {data:profiles,error:profileError}=await window.rkSupabase.from('profiles').select('id,username').ilike('username',username).limit(1);if(profileError)throw profileError;const profile=profiles?.[0];if(!profile){titleEl.innerHTML='<p class="no-titles">No site titles held yet.</p>';return;}const {data:titles,error}=await window.rkSupabase.from('titles').select('title,awarded_at').eq('user_id',profile.id).order('awarded_at',{ascending:true});if(error)throw error;const rows=Array.isArray(titles)?titles:[];if(!rows.length){titleEl.innerHTML='<p class="no-titles">No site titles held yet.</p>';return;}const badgeMap={RKWC:'badge-special',RKSGM:'badge-elite',RKGM:'badge-grand',RKIM:'badge-master',RKM:'badge-candidate',RKCM:'badge-clight',RKV:'badge-veteran',RKHM:'badge-special'};titleEl.innerHTML='<div class="site-titles-list">'+rows.map(row=>{const code=String(row.title||'').toUpperCase();const date=row.awarded_at?new Date(row.awarded_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'';return `<span class="site-title-badge ${badgeMap[code]||'badge-veteran'}">${code}${date?`<span class="since-label">· ${date}</span>`:''}</span>`;}).join('')+'</div>';}catch(e){console.warn('Could not sync profile titles from Supabase:',e);}};
    window.openApplyModal=function(){const overlay=document.getElementById('applyModal'),body=document.getElementById('applyModalBody');if(!overlay||!body)return;const profileUser=document.getElementById('usernameInput')?.value?.trim()||'';if(!user){body.innerHTML='<div class="modal-info">You need a site account to apply for a title.</div><div class="modal-actions"><button class="modal-cancel-btn" onclick="closeApplyModal()">Close</button><button class="modal-submit-btn" onclick="window.location.href=\'auth.html\'">Login / Register</button></div>';overlay.classList.remove('hidden');return;}if(!profileUser||String(user.username).toLowerCase()!==profileUser.toLowerCase()){body.innerHTML=`<div class="modal-info">You're logged in as <strong>${user.username}</strong>. You can only apply for your own title. Load your own profile first.</div><div class="modal-actions"><button class="modal-cancel-btn" onclick="closeApplyModal()">Close</button><button class="modal-submit-btn" onclick="document.getElementById('usernameInput').value='${String(user.username).replace(/'/g,"\\'")}';closeApplyModal();loadProfile('${String(user.username).replace(/'/g,"\\'")}')">Load My Profile</button></div>`;overlay.classList.remove('hidden');return;}const stats=readProfileStats();const defs=[['RKSGM','Super Grandmaster',5000,2500],['RKGM','Grandmaster',5000,2400],['RKIM','International Master',3000,2300],['RKM','Master',1000,2200],['RKCM','Candidate Master',500,2100],['RKV','Veteran',10000,0]];const first=defs.find(d=>stats.games>=d[2]&&(d[3]===0||stats.peakRating>=d[3]))||defs[defs.length-2];overlay.classList.remove('hidden');body.innerHTML=`<div class="modal-field"><label class="modal-label">Lichess Username</label><input class="modal-input" value="${profileUser.replace(/"/g,'&quot;')}" readonly /></div><div class="modal-field"><label class="modal-label">Title Applying For</label><select class="modal-select" id="applyTitleSelect" onchange="updateApplyStats()">${defs.map(d=>`<option value="${d[0]}" ${d[0]===first[0]?'selected':''}>${d[0]} — ${d[1]}</option>`).join('')}</select></div><div class="modal-stats" id="applyStatsBox"></div><div class="modal-field"><label class="modal-label">Message (optional)</label><textarea class="modal-textarea" id="applyMessage" placeholder="Any additional context for the admin…"></textarea></div><div class="modal-info">Your current Lichess stats are included automatically. Tournament norms are reviewed by an admin. RKWC and RKHM are manually awarded and are not automatic applications.</div><div id="applyFeedback" style="margin-bottom:.75rem;font-size:.84rem;display:none"></div><div class="modal-actions"><button class="modal-cancel-btn" onclick="closeApplyModal()">Cancel</button><button class="modal-submit-btn" id="applySubmitBtn" onclick="submitTitleApplication()">Submit Application</button></div>`;window.updateApplyStats();};
    window.updateApplyStats=function(){const box=document.getElementById('applyStatsBox');if(!box)return;const code=document.getElementById('applyTitleSelect')?.value;const defs={RKSGM:[5000,2500],RKGM:[5000,2400],RKIM:[3000,2300],RKM:[1000,2200],RKCM:[500,2100],RKV:[10000,0]};const def=defs[code];const stats=readProfileStats();if(!def){box.innerHTML='';return;}const gOk=stats.games>=def[0],rOk=def[1]===0||stats.peakRating>=def[1];box.innerHTML=`<div class="modal-stat-row"><span class="modal-stat-label">RK games</span><span class="modal-stat-val ${gOk?'met':'unmet'}">${stats.games.toLocaleString()} / ${def[0].toLocaleString()} ${gOk?'✓':'✗'}</span></div><div class="modal-stat-row"><span class="modal-stat-label">Peak rating</span><span class="modal-stat-val ${rOk?'met':'unmet'}">${def[1]===0?'No rating req':`${stats.peakRating} / ${def[1]} ${rOk?'✓':'✗'}`}</span></div><div class="modal-stat-row" style="margin-top:.3rem;padding-top:.3rem;border-top:1px solid var(--border)"><span class="modal-stat-label" style="font-size:.76rem">Tournament norms</span><span style="font-size:.76rem;color:var(--text-muted)">Verified by admin</span></div>`;};
    window.submitTitleApplication=async function(){const btn=document.getElementById('applySubmitBtn'),feedback=document.getElementById('applyFeedback'),titleCode=document.getElementById('applyTitleSelect')?.value,message=(document.getElementById('applyMessage')?.value||'').trim();if(!btn||!feedback||!titleCode||!user?.id)return;const stats=readProfileStats();btn.disabled=true;btn.textContent='Submitting…';feedback.style.display='none';try{const {data:existing,error:existingError}=await window.rkSupabase.from('title_applications').select('id').eq('user_id',user.id).eq('title_code',titleCode).eq('status','pending').limit(1);if(existingError)throw existingError;if(existing?.length)throw new Error('You already have a pending application for this title.');const {error}=await window.rkSupabase.from('title_applications').insert({user_id:user.id,title_code:titleCode,message,games:stats.games,peak_rating:stats.peakRating});if(error)throw error;feedback.textContent='✓ Application submitted! The admin will review it shortly.';feedback.style.color='#4ade80';feedback.style.display='block';btn.textContent='Submitted';}catch(e){feedback.textContent=e.message||'Submission failed.';feedback.style.color='#f87171';feedback.style.display='block';btn.disabled=false;btn.textContent='Submit Application';}};
    if(typeof window.loadProfile==='function'&&!window.__rkProfileLoadWrapped){const originalLoadProfile=window.loadProfile;window.loadProfile=async function(...args){const result=await originalLoadProfile.apply(this,args);await refreshProfileTitles();return result;};window.__rkProfileLoadWrapped=true;}
    if(typeof window.loadProfile==='function'&&!document.getElementById('usernameInput')?.value&&user?.username)document.getElementById('usernameInput').value=user.username;
    await refreshProfileTitles();
  }
  function fixLegacyCheckerLinks(){document.querySelectorAll('a[href="search.html"]').forEach(a=>{a.href='title-checker.html';});}
  async function auth(){const right=document.querySelector('.nav-right'),menuBtn=document.getElementById('menuBtn');let user=null;try{await deps();const s=await window.rkAuth.session();if(s)user=await window.rkAuth.user();}catch(e){console.warn(e);}let b=document.getElementById('navAuthBtn');if(!b&&right){b=document.createElement('button');b.className='icon-btn';b.id='navAuthBtn';b.type='button';right.insertBefore(b,menuBtn||null);}if(b){b.textContent=user?'👤 '+user.username:'Login';b.onclick=()=>location.href=user?'settings.html':'auth.html';}}
  function buildMenu(){const panel=document.getElementById('menuPanel');if(!panel)return;panel.innerHTML='';const home=makeLink('Home','index.html');home.className='menu-home';panel.appendChild(home);RK_MENU_GROUPS.forEach(group=>{const section=document.createElement('div');section.className='menu-section';section.dataset.menuGroup=group.label;const heading=makeLink(group.label,pageUrl(group.slug));heading.className='menu-section-link';heading.setAttribute('aria-label','Open '+group.label+' menu');section.appendChild(heading);panel.appendChild(section);});}
  async function init(){logo();const panel=document.getElementById('menuPanel'),btn=document.getElementById('menuBtn');if(!panel||!btn)return;buildMenu();await auth();fixLegacyCheckerLinks();await syncHomepageTitleStats();await syncTitlesPage();await syncProfilePage(await window.rkAuth.user().catch(()=>null));btn.onclick=e=>{e.stopPropagation();panel.classList.toggle('open');};document.addEventListener('click',e=>{if(!panel.contains(e.target)&&!btn.contains(e.target))panel.classList.remove('open');});if(!window.rkSupabase)await deps();await loadScript('js/notifications.js');if(window.rkSupabase)window.rkSupabase.auth.onAuthStateChange(()=>setTimeout(auth,0));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
