const TEAM='the-racing-kings-master';const API=`https://lichess.org/api/team/${TEAM}`;const USERS=`https://lichess.org/api/team/${TEAM}/users`;let members=[];
const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};
async function fetchTeam(){const r=await fetch(API,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`Team request failed (${r.status})`);return r.json()}
async function fetchMembers(){const r=await fetch(USERS,{headers:{Accept:'application/x-ndjson, application/json'}});if(!r.ok)throw Error(`Member request failed (${r.status})`);const t=await r.text();try{const j=JSON.parse(t);return Array.isArray(j)?j:[j]}catch{return t.split(/\r?\n/).filter(Boolean).map(JSON.parse)}}
const rating=u=>Number.isFinite(Number(u?.perfs?.racingKings?.rating))?Number(u.perfs.racingKings.rating):null;
function stats(){const rs=members.map(rating).filter(Number.isFinite);document.getElementById('memberCount').textContent=members.length.toLocaleString();document.getElementById('rkRatedCount').textContent=rs.length.toLocaleString();document.getElementById('averageRating').textContent=rs.length?Math.round(rs.reduce((a,b)=>a+b,0)/rs.length).toLocaleString():'—';document.getElementById('highestRating').textContent=rs.length?Math.max(...rs).toLocaleString():'—'}
function leaders(team){const a=Array.isArray(team?.leaders)?team.leaders:team?.leader?[team.leader]:[];const names=[...new Set(a.map(x=>typeof x==='string'?x:x?.username).filter(Boolean))];document.getElementById('leadersList').innerHTML=names.length?names.map(n=>`<div class="leader-row"><span class="leader-badge">Leader</span><a class="leader-name" href="https://lichess.org/@/${encodeURIComponent(n)}" target="_blank" rel="noopener">${esc(n)}</a></div>`).join(''):'<div class="empty">Leadership information unavailable.</div>'}
function render(){let a=members.filter(u=>String(u.username||'').toLowerCase().includes(document.getElementById('memberSearch').value.trim().toLowerCase()));const sort=document.getElementById('memberSort').value;a.sort((x,y)=>sort==='name'?String(x.username).localeCompare(String(y.username)):sort==='title'?String(x.title||'').localeCompare(String(y.title||'')):((rating(y)??-1)-(rating(x)??-1))||String(x.username).localeCompare(String(y.username)));document.getElementById('membersList').innerHTML=a.length?a.map(u=>{const n=String(u.username||'Unknown'),r=rating(u),t=u.title?String(u.title):'';return `<a class="member-row" href="https://lichess.org/@/${encodeURIComponent(n)}" target="_blank" rel="noopener"><span class="member-avatar">${esc(n[0]?.toUpperCase())}</span><span class="member-name">${esc(n)}</span><span class="member-title">${esc(t||'RK')}</span><span class="member-rating">${r?r.toLocaleString():'—'}</span></a>`}).join(''):'<div class="empty">No members match that search.</div>';document.getElementById('membersMore').textContent=`${a.length.toLocaleString()} member${a.length===1?'':'s'} shown`}
async function load(){try{const team=await fetchTeam();leaders(team);if(team?.name)document.getElementById('teamName').textContent=team.name;if(team?.description)document.getElementById('teamDescription').textContent=team.description;members=await fetchMembers();stats();render();document.getElementById('memberUpdated').textContent=`Updated ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}catch(e){console.error(e);document.getElementById('leadersList').innerHTML='<div class="error-box">Live Lichess team data could not be loaded right now.</div>';document.getElementById('membersList').innerHTML='<div class="error-box">Live member data could not be loaded. Please try again shortly.</div>';document.getElementById('memberUpdated').textContent='Live data unavailable'}}
document.getElementById('memberSearch')?.addEventListener('input',render);document.getElementById('memberSort')?.addEventListener('change',render);load();