// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/leaderboard-redesign/ArenaLeaderboard.tsx": () => import("../components/mockups/leaderboard-redesign/ArenaLeaderboard.tsx"),
  "./components/mockups/leaderboard-redesign/CompetitiveTable.tsx": () => import("../components/mockups/leaderboard-redesign/CompetitiveTable.tsx"),
  "./components/mockups/leaderboard-redesign/SeasonHub.tsx": () => import("../components/mockups/leaderboard-redesign/SeasonHub.tsx")
};
